Sample added
After scala version update to 2.13.7, compilation error occurs:

[error] /home/mirek/fpflatmap/FpFlatMap.scala:10:32: could not find implicit value for evidence parameter of type fastparse.P[_]
[error]   def flat[_:P] = left.flatMap(right)
[error]                                ^